"""SSH-ключі для codex-агента — живуть файлами у shared volume, що
змонтований у codex-cli як `~/.ssh`. Add пише `id_<name>` (0600) і
перегенерує `config` (один Host-блок на ключ; `Host <name> <host>` —
підхоплюється і по аліасу, і по прямому хосту). Агент клонує/конектиться
одразу, без рестарту. Named volume переживає пересоздання, БД не потрібна.
"""

from datetime import UTC, datetime
from pathlib import Path

import orjson
from pydantic import BaseModel, ConfigDict

from app.services.ssh_vault._common import (
    SshVaultError,
    resolve_user,
    validate_host,
    validate_name,
    vault_lock,
    write_secret,
)

__all__ = ["SshKeyMeta", "SshVaultError", "SshVaultService"]

_DEFAULT_USER = "git"
_INDEX_FILE = "vault.json"
_CONFIG_FILE = "config"
_KEY_PREFIX = "id_"
_HOST_BLOCK = (
    "\nHost {name} {host}\n"
    "    HostName {host}\n"
    "    User {user}\n"
    "    IdentityFile ~/.ssh/{prefix}{name}\n"
    "    IdentitiesOnly yes\n"
    "    StrictHostKeyChecking accept-new\n"
)
_CONFIG_HEADER = "# generated by codex-server — do not edit by hand\n"


class SshKeyMeta(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    host: str
    user: str
    created_at: datetime


class SshVaultService:
    """Stateless over the vault dir — single source of truth is the filesystem."""

    def __init__(self, vault_dir: Path) -> None:
        self._dir = vault_dir

    def add(self, *, name: str, host: str, user: str, private_key: str) -> SshKeyMeta:
        name = validate_name(name.strip())
        host = validate_host(host.strip())
        user = resolve_user(user.strip(), _DEFAULT_USER)
        key = private_key.strip()
        if "PRIVATE KEY" not in key:
            raise SshVaultError("private_key is not an OpenSSH/PEM private key")

        with vault_lock(self._dir):
            index = self._read_index()
            meta = SshKeyMeta(name=name, host=host, user=user, created_at=datetime.now(UTC))
            index[name] = meta
            write_secret(self._key_path(name), key + "\n")
            self._write_index(index)
            self._write_config(index)
        return meta

    def list(self) -> list[SshKeyMeta]:
        return sorted(self._read_index().values(), key=lambda m: m.name)

    def delete(self, name: str) -> None:
        with vault_lock(self._dir):
            index = self._read_index()
            if name not in index:
                raise SshVaultError(f"unknown key: {name}")
            del index[name]
            self._key_path(name).unlink(missing_ok=True)
            self._write_index(index)
            self._write_config(index)

    def _key_path(self, name: str) -> Path:
        return self._dir / f"{_KEY_PREFIX}{name}"

    def _read_index(self) -> dict[str, SshKeyMeta]:
        path = self._dir / _INDEX_FILE
        if not path.exists():
            return {}
        raw: dict[str, object] = orjson.loads(path.read_bytes())
        return {name: SshKeyMeta.model_validate(meta) for name, meta in raw.items()}

    def _write_index(self, index: dict[str, SshKeyMeta]) -> None:
        payload = {name: meta.model_dump(mode="json") for name, meta in index.items()}
        write_secret(self._dir / _INDEX_FILE, orjson.dumps(payload).decode())

    def _write_config(self, index: dict[str, SshKeyMeta]) -> None:
        body = _CONFIG_HEADER + "".join(
            _HOST_BLOCK.format(name=m.name, host=m.host, user=m.user, prefix=_KEY_PREFIX)
            for m in sorted(index.values(), key=lambda m: m.name)
        )
        write_secret(self._dir / _CONFIG_FILE, body)
