"""init

Revision ID: 94a3a0c51483
Revises: 
Create Date: 2026-05-06 17:13:17.176657
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '94a3a0c51483'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_msg_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', title || ' ' || body)", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_search_vector', 'notes', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_notes_tags', 'notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conv_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conv_id'), 'messages', ['conv_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conv_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime', sa.String(length=127), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('s3_path', sa.String(length=1024), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_conv_id'), 'uploads', ['conv_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_conv_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_messages_conv_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_notes_tags', table_name='notes', postgresql_using='gin')
    op.drop_index('ix_notes_search_vector', table_name='notes', postgresql_using='gin')
    op.drop_table('notes')
    op.drop_table('conversations')
    # ### end Alembic commands ###
