"""init schema

Revision ID: d229700c948e
Revises: 
Create Date: 2026-05-28 19:59:03.967416
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd229700c948e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), server_default='USER', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.create_table('chats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('WEB', 'TELEGRAM', name='chat_source'), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_message_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('codex_thread_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('last_msg_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_index('uq_chats_tg_chat_thread', 'chats', ['tg_chat_id', 'tg_message_thread_id'], unique=True, postgresql_where=sa.text("source = 'TELEGRAM'"), postgresql_nulls_not_distinct=True)
    op.create_table('invites',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('used_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    op.create_table('notebooks',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('PERSONAL', name='notebook_kind'), server_default='PERSONAL', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', name='uq_notebooks_user_kind')
    )
    op.create_index(op.f('ix_notebooks_user_id'), 'notebooks', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('notebook_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', title || ' ' || body)", persisted=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_notebook_id'), 'notes', ['notebook_id'], unique=False)
    op.create_index('ix_notes_search_vector', 'notes', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_notes_tags', 'notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('THREAD_OPENED', 'THREAD_RESET', 'THREAD_LOST', 'TURN_STARTED', 'TURN_COMPLETED', 'TURN_INTERRUPTED', 'TURN_FAILED', 'ATTACHMENT_RECEIVED', 'AUDIO_TRANSCRIBED', 'ERROR', name='event_kind'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_chat_id'), 'events', ['chat_id'], unique=False)
    op.create_index(op.f('ix_events_kind'), 'events', ['kind'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_table('uploads',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime', sa.String(length=127), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('s3_path', sa.String(length=1024), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_chat_id'), 'uploads', ['chat_id'], unique=False)
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_table('turns',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_message_id', sa.BigInteger(), nullable=False),
    sa.Column('assistant_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('STARTING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='turn_status'), nullable=False),
    sa.Column('codex_thread_id', sa.Text(), nullable=True),
    sa.Column('codex_turn_id', sa.Text(), nullable=True),
    sa.Column('sidecar', sa.Text(), nullable=True),
    sa.Column('stream_key', sa.Text(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('last_event_id', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('turns_active_per_chat', 'turns', ['chat_id'], unique=True, postgresql_where="status IN ('STARTING', 'RUNNING')")
    op.create_index('turns_by_chat', 'turns', ['chat_id', 'created_at'], unique=False)
    op.create_index('turns_by_user', 'turns', ['user_id', 'created_at'], unique=False)
    op.create_index('turns_stale_heartbeat', 'turns', ['heartbeat_at'], unique=False, postgresql_where="status = 'RUNNING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('turns_stale_heartbeat', table_name='turns', postgresql_where="status = 'RUNNING'")
    op.drop_index('turns_by_user', table_name='turns')
    op.drop_index('turns_by_chat', table_name='turns')
    op.drop_index('turns_active_per_chat', table_name='turns', postgresql_where="status IN ('STARTING', 'RUNNING')")
    op.drop_table('turns')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_chat_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_kind'), table_name='events')
    op.drop_index(op.f('ix_events_chat_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index('ix_notes_tags', table_name='notes', postgresql_using='gin')
    op.drop_index('ix_notes_search_vector', table_name='notes', postgresql_using='gin')
    op.drop_index(op.f('ix_notes_notebook_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_notebooks_user_id'), table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_table('invites')
    op.drop_index('uq_chats_tg_chat_thread', table_name='chats', postgresql_where=sa.text("source = 'TELEGRAM'"), postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
