# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/admin.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.admin_pb2 as codex_dot_v1_dot_admin__pb2
import codex.v1.common_pb2 as codex_dot_v1_dot_common__pb2


class AdminService(Protocol):
    async def create_invite(self, request: codex_dot_v1_dot_admin__pb2.CreateInviteRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.CreateInviteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_invites(self, request: codex_dot_v1_dot_admin__pb2.ListInvitesRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListInvitesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def revoke_invite(self, request: codex_dot_v1_dot_admin__pb2.RevokeInviteRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_user(self, request: codex_dot_v1_dot_admin__pb2.CreateUserRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.AdminUser:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_users(self, request: codex_dot_v1_dot_admin__pb2.ListUsersRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AdminServiceASGIApplication(ConnectASGIApplication[AdminService]):
    def __init__(self, service: AdminService | AsyncGenerator[AdminService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.AdminService/CreateInvite": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateInvite",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
                        output=codex_dot_v1_dot_admin__pb2.CreateInviteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_invite,
                ),
                "/codex.v1.AdminService/ListInvites": Endpoint.unary(
                    method=MethodInfo(
                        name="ListInvites",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListInvitesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_invites,
                ),
                "/codex.v1.AdminService/RevokeInvite": Endpoint.unary(
                    method=MethodInfo(
                        name="RevokeInvite",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.revoke_invite,
                ),
                "/codex.v1.AdminService/CreateUser": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateUser",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.CreateUserRequest,
                        output=codex_dot_v1_dot_admin__pb2.AdminUser,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_user,
                ),
                "/codex.v1.AdminService/ListUsers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListUsers",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListUsersRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_users,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.AdminService"


class AdminServiceClient(ConnectClient):
    async def create_invite(
        self,
        request: codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.CreateInviteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateInvite",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
                output=codex_dot_v1_dot_admin__pb2.CreateInviteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_invites(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListInvitesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListInvites",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
                output=codex_dot_v1_dot_admin__pb2.ListInvitesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def revoke_invite(
        self,
        request: codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeInvite",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_user(
        self,
        request: codex_dot_v1_dot_admin__pb2.CreateUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.AdminUser:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateUser",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.CreateUserRequest,
                output=codex_dot_v1_dot_admin__pb2.AdminUser,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_users(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListUsersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListUsersRequest,
                output=codex_dot_v1_dot_admin__pb2.ListUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class AdminServiceSync(Protocol):
    def create_invite(self, request: codex_dot_v1_dot_admin__pb2.CreateInviteRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.CreateInviteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_invites(self, request: codex_dot_v1_dot_admin__pb2.ListInvitesRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListInvitesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def revoke_invite(self, request: codex_dot_v1_dot_admin__pb2.RevokeInviteRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_user(self, request: codex_dot_v1_dot_admin__pb2.CreateUserRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.AdminUser:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_users(self, request: codex_dot_v1_dot_admin__pb2.ListUsersRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AdminServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AdminServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.AdminService/CreateInvite": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateInvite",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
                        output=codex_dot_v1_dot_admin__pb2.CreateInviteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_invite,
                ),
                "/codex.v1.AdminService/ListInvites": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListInvites",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListInvitesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_invites,
                ),
                "/codex.v1.AdminService/RevokeInvite": EndpointSync.unary(
                    method=MethodInfo(
                        name="RevokeInvite",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.revoke_invite,
                ),
                "/codex.v1.AdminService/CreateUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateUser",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.CreateUserRequest,
                        output=codex_dot_v1_dot_admin__pb2.AdminUser,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_user,
                ),
                "/codex.v1.AdminService/ListUsers": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListUsers",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListUsersRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_users,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.AdminService"


class AdminServiceClientSync(ConnectClientSync):
    def create_invite(
        self,
        request: codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.CreateInviteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateInvite",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
                output=codex_dot_v1_dot_admin__pb2.CreateInviteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_invites(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListInvitesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListInvites",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
                output=codex_dot_v1_dot_admin__pb2.ListInvitesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def revoke_invite(
        self,
        request: codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeInvite",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_user(
        self,
        request: codex_dot_v1_dot_admin__pb2.CreateUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.AdminUser:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateUser",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.CreateUserRequest,
                output=codex_dot_v1_dot_admin__pb2.AdminUser,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_users(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListUsersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListUsersRequest,
                output=codex_dot_v1_dot_admin__pb2.ListUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


