# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/admin.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.admin_pb2 as codex_dot_v1_dot_admin__pb2
import codex.v1.common_pb2 as codex_dot_v1_dot_common__pb2


class AdminService(Protocol):
    async def create_invite(self, request: codex_dot_v1_dot_admin__pb2.CreateInviteRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.CreateInviteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_invites(self, request: codex_dot_v1_dot_admin__pb2.ListInvitesRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListInvitesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def revoke_invite(self, request: codex_dot_v1_dot_admin__pb2.RevokeInviteRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_user(self, request: codex_dot_v1_dot_admin__pb2.CreateUserRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.AdminUser:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_users(self, request: codex_dot_v1_dot_admin__pb2.ListUsersRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def add_ssh_key(self, request: codex_dot_v1_dot_admin__pb2.AddSshKeyRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.SshKey:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_ssh_keys(self, request: codex_dot_v1_dot_admin__pb2.ListSshKeysRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListSshKeysResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_ssh_key(self, request: codex_dot_v1_dot_admin__pb2.DeleteSshKeyRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def add_api_token(self, request: codex_dot_v1_dot_admin__pb2.AddApiTokenRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ApiToken:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_api_tokens(self, request: codex_dot_v1_dot_admin__pb2.ListApiTokensRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListApiTokensResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_api_token(self, request: codex_dot_v1_dot_admin__pb2.DeleteApiTokenRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AdminServiceASGIApplication(ConnectASGIApplication[AdminService]):
    def __init__(self, service: AdminService | AsyncGenerator[AdminService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.AdminService/CreateInvite": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateInvite",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
                        output=codex_dot_v1_dot_admin__pb2.CreateInviteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_invite,
                ),
                "/codex.v1.AdminService/ListInvites": Endpoint.unary(
                    method=MethodInfo(
                        name="ListInvites",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListInvitesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_invites,
                ),
                "/codex.v1.AdminService/RevokeInvite": Endpoint.unary(
                    method=MethodInfo(
                        name="RevokeInvite",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.revoke_invite,
                ),
                "/codex.v1.AdminService/CreateUser": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateUser",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.CreateUserRequest,
                        output=codex_dot_v1_dot_admin__pb2.AdminUser,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_user,
                ),
                "/codex.v1.AdminService/ListUsers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListUsers",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListUsersRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_users,
                ),
                "/codex.v1.AdminService/AddSshKey": Endpoint.unary(
                    method=MethodInfo(
                        name="AddSshKey",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.AddSshKeyRequest,
                        output=codex_dot_v1_dot_admin__pb2.SshKey,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.add_ssh_key,
                ),
                "/codex.v1.AdminService/ListSshKeys": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSshKeys",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListSshKeysRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListSshKeysResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_ssh_keys,
                ),
                "/codex.v1.AdminService/DeleteSshKey": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteSshKey",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.DeleteSshKeyRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_ssh_key,
                ),
                "/codex.v1.AdminService/AddApiToken": Endpoint.unary(
                    method=MethodInfo(
                        name="AddApiToken",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.AddApiTokenRequest,
                        output=codex_dot_v1_dot_admin__pb2.ApiToken,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.add_api_token,
                ),
                "/codex.v1.AdminService/ListApiTokens": Endpoint.unary(
                    method=MethodInfo(
                        name="ListApiTokens",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListApiTokensRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListApiTokensResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_api_tokens,
                ),
                "/codex.v1.AdminService/DeleteApiToken": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteApiToken",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.DeleteApiTokenRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_api_token,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.AdminService"


class AdminServiceClient(ConnectClient):
    async def create_invite(
        self,
        request: codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.CreateInviteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateInvite",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
                output=codex_dot_v1_dot_admin__pb2.CreateInviteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_invites(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListInvitesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListInvites",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
                output=codex_dot_v1_dot_admin__pb2.ListInvitesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def revoke_invite(
        self,
        request: codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeInvite",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_user(
        self,
        request: codex_dot_v1_dot_admin__pb2.CreateUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.AdminUser:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateUser",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.CreateUserRequest,
                output=codex_dot_v1_dot_admin__pb2.AdminUser,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_users(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListUsersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListUsersRequest,
                output=codex_dot_v1_dot_admin__pb2.ListUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def add_ssh_key(
        self,
        request: codex_dot_v1_dot_admin__pb2.AddSshKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.SshKey:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddSshKey",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.AddSshKeyRequest,
                output=codex_dot_v1_dot_admin__pb2.SshKey,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_ssh_keys(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListSshKeysRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListSshKeysResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSshKeys",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListSshKeysRequest,
                output=codex_dot_v1_dot_admin__pb2.ListSshKeysResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_ssh_key(
        self,
        request: codex_dot_v1_dot_admin__pb2.DeleteSshKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSshKey",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.DeleteSshKeyRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def add_api_token(
        self,
        request: codex_dot_v1_dot_admin__pb2.AddApiTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ApiToken:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddApiToken",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.AddApiTokenRequest,
                output=codex_dot_v1_dot_admin__pb2.ApiToken,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_api_tokens(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListApiTokensRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListApiTokensResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListApiTokens",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListApiTokensRequest,
                output=codex_dot_v1_dot_admin__pb2.ListApiTokensResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_api_token(
        self,
        request: codex_dot_v1_dot_admin__pb2.DeleteApiTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteApiToken",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.DeleteApiTokenRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class AdminServiceSync(Protocol):
    def create_invite(self, request: codex_dot_v1_dot_admin__pb2.CreateInviteRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.CreateInviteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_invites(self, request: codex_dot_v1_dot_admin__pb2.ListInvitesRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListInvitesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def revoke_invite(self, request: codex_dot_v1_dot_admin__pb2.RevokeInviteRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_user(self, request: codex_dot_v1_dot_admin__pb2.CreateUserRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.AdminUser:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_users(self, request: codex_dot_v1_dot_admin__pb2.ListUsersRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def add_ssh_key(self, request: codex_dot_v1_dot_admin__pb2.AddSshKeyRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.SshKey:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_ssh_keys(self, request: codex_dot_v1_dot_admin__pb2.ListSshKeysRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListSshKeysResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_ssh_key(self, request: codex_dot_v1_dot_admin__pb2.DeleteSshKeyRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def add_api_token(self, request: codex_dot_v1_dot_admin__pb2.AddApiTokenRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ApiToken:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_api_tokens(self, request: codex_dot_v1_dot_admin__pb2.ListApiTokensRequest, ctx: RequestContext) -> codex_dot_v1_dot_admin__pb2.ListApiTokensResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_api_token(self, request: codex_dot_v1_dot_admin__pb2.DeleteApiTokenRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AdminServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AdminServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.AdminService/CreateInvite": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateInvite",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
                        output=codex_dot_v1_dot_admin__pb2.CreateInviteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_invite,
                ),
                "/codex.v1.AdminService/ListInvites": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListInvites",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListInvitesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_invites,
                ),
                "/codex.v1.AdminService/RevokeInvite": EndpointSync.unary(
                    method=MethodInfo(
                        name="RevokeInvite",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.revoke_invite,
                ),
                "/codex.v1.AdminService/CreateUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateUser",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.CreateUserRequest,
                        output=codex_dot_v1_dot_admin__pb2.AdminUser,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_user,
                ),
                "/codex.v1.AdminService/ListUsers": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListUsers",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListUsersRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_users,
                ),
                "/codex.v1.AdminService/AddSshKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="AddSshKey",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.AddSshKeyRequest,
                        output=codex_dot_v1_dot_admin__pb2.SshKey,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.add_ssh_key,
                ),
                "/codex.v1.AdminService/ListSshKeys": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSshKeys",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListSshKeysRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListSshKeysResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_ssh_keys,
                ),
                "/codex.v1.AdminService/DeleteSshKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteSshKey",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.DeleteSshKeyRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_ssh_key,
                ),
                "/codex.v1.AdminService/AddApiToken": EndpointSync.unary(
                    method=MethodInfo(
                        name="AddApiToken",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.AddApiTokenRequest,
                        output=codex_dot_v1_dot_admin__pb2.ApiToken,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.add_api_token,
                ),
                "/codex.v1.AdminService/ListApiTokens": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListApiTokens",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.ListApiTokensRequest,
                        output=codex_dot_v1_dot_admin__pb2.ListApiTokensResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_api_tokens,
                ),
                "/codex.v1.AdminService/DeleteApiToken": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteApiToken",
                        service_name="codex.v1.AdminService",
                        input=codex_dot_v1_dot_admin__pb2.DeleteApiTokenRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_api_token,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.AdminService"


class AdminServiceClientSync(ConnectClientSync):
    def create_invite(
        self,
        request: codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.CreateInviteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateInvite",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.CreateInviteRequest,
                output=codex_dot_v1_dot_admin__pb2.CreateInviteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_invites(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListInvitesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListInvites",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListInvitesRequest,
                output=codex_dot_v1_dot_admin__pb2.ListInvitesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def revoke_invite(
        self,
        request: codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeInvite",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.RevokeInviteRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_user(
        self,
        request: codex_dot_v1_dot_admin__pb2.CreateUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.AdminUser:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateUser",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.CreateUserRequest,
                output=codex_dot_v1_dot_admin__pb2.AdminUser,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_users(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListUsersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListUsersRequest,
                output=codex_dot_v1_dot_admin__pb2.ListUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def add_ssh_key(
        self,
        request: codex_dot_v1_dot_admin__pb2.AddSshKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.SshKey:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddSshKey",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.AddSshKeyRequest,
                output=codex_dot_v1_dot_admin__pb2.SshKey,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_ssh_keys(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListSshKeysRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListSshKeysResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSshKeys",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListSshKeysRequest,
                output=codex_dot_v1_dot_admin__pb2.ListSshKeysResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_ssh_key(
        self,
        request: codex_dot_v1_dot_admin__pb2.DeleteSshKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSshKey",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.DeleteSshKeyRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def add_api_token(
        self,
        request: codex_dot_v1_dot_admin__pb2.AddApiTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ApiToken:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddApiToken",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.AddApiTokenRequest,
                output=codex_dot_v1_dot_admin__pb2.ApiToken,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_api_tokens(
        self,
        request: codex_dot_v1_dot_admin__pb2.ListApiTokensRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_admin__pb2.ListApiTokensResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListApiTokens",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.ListApiTokensRequest,
                output=codex_dot_v1_dot_admin__pb2.ListApiTokensResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_api_token(
        self,
        request: codex_dot_v1_dot_admin__pb2.DeleteApiTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteApiToken",
                service_name="codex.v1.AdminService",
                input=codex_dot_v1_dot_admin__pb2.DeleteApiTokenRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


