# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/auth.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.auth_pb2 as codex_dot_v1_dot_auth__pb2


class AuthService(Protocol):
    async def login(self, request: codex_dot_v1_dot_auth__pb2.LoginRequest, ctx: RequestContext) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def register(self, request: codex_dot_v1_dot_auth__pb2.RegisterRequest, ctx: RequestContext) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def refresh(self, request: codex_dot_v1_dot_auth__pb2.RefreshRequest, ctx: RequestContext) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def logout(self, request: codex_dot_v1_dot_auth__pb2.LogoutRequest, ctx: RequestContext) -> codex_dot_v1_dot_auth__pb2.LogoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AuthServiceASGIApplication(ConnectASGIApplication[AuthService]):
    def __init__(self, service: AuthService | AsyncGenerator[AuthService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.AuthService/Login": Endpoint.unary(
                    method=MethodInfo(
                        name="Login",
                        service_name="codex.v1.AuthService",
                        input=codex_dot_v1_dot_auth__pb2.LoginRequest,
                        output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.login,
                ),
                "/codex.v1.AuthService/Register": Endpoint.unary(
                    method=MethodInfo(
                        name="Register",
                        service_name="codex.v1.AuthService",
                        input=codex_dot_v1_dot_auth__pb2.RegisterRequest,
                        output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.register,
                ),
                "/codex.v1.AuthService/Refresh": Endpoint.unary(
                    method=MethodInfo(
                        name="Refresh",
                        service_name="codex.v1.AuthService",
                        input=codex_dot_v1_dot_auth__pb2.RefreshRequest,
                        output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.refresh,
                ),
                "/codex.v1.AuthService/Logout": Endpoint.unary(
                    method=MethodInfo(
                        name="Logout",
                        service_name="codex.v1.AuthService",
                        input=codex_dot_v1_dot_auth__pb2.LogoutRequest,
                        output=codex_dot_v1_dot_auth__pb2.LogoutResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.logout,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.AuthService"


class AuthServiceClient(ConnectClient):
    async def login(
        self,
        request: codex_dot_v1_dot_auth__pb2.LoginRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Login",
                service_name="codex.v1.AuthService",
                input=codex_dot_v1_dot_auth__pb2.LoginRequest,
                output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def register(
        self,
        request: codex_dot_v1_dot_auth__pb2.RegisterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Register",
                service_name="codex.v1.AuthService",
                input=codex_dot_v1_dot_auth__pb2.RegisterRequest,
                output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def refresh(
        self,
        request: codex_dot_v1_dot_auth__pb2.RefreshRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Refresh",
                service_name="codex.v1.AuthService",
                input=codex_dot_v1_dot_auth__pb2.RefreshRequest,
                output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def logout(
        self,
        request: codex_dot_v1_dot_auth__pb2.LogoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_auth__pb2.LogoutResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Logout",
                service_name="codex.v1.AuthService",
                input=codex_dot_v1_dot_auth__pb2.LogoutRequest,
                output=codex_dot_v1_dot_auth__pb2.LogoutResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class AuthServiceSync(Protocol):
    def login(self, request: codex_dot_v1_dot_auth__pb2.LoginRequest, ctx: RequestContext) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def register(self, request: codex_dot_v1_dot_auth__pb2.RegisterRequest, ctx: RequestContext) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def refresh(self, request: codex_dot_v1_dot_auth__pb2.RefreshRequest, ctx: RequestContext) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def logout(self, request: codex_dot_v1_dot_auth__pb2.LogoutRequest, ctx: RequestContext) -> codex_dot_v1_dot_auth__pb2.LogoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AuthServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AuthServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.AuthService/Login": EndpointSync.unary(
                    method=MethodInfo(
                        name="Login",
                        service_name="codex.v1.AuthService",
                        input=codex_dot_v1_dot_auth__pb2.LoginRequest,
                        output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.login,
                ),
                "/codex.v1.AuthService/Register": EndpointSync.unary(
                    method=MethodInfo(
                        name="Register",
                        service_name="codex.v1.AuthService",
                        input=codex_dot_v1_dot_auth__pb2.RegisterRequest,
                        output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.register,
                ),
                "/codex.v1.AuthService/Refresh": EndpointSync.unary(
                    method=MethodInfo(
                        name="Refresh",
                        service_name="codex.v1.AuthService",
                        input=codex_dot_v1_dot_auth__pb2.RefreshRequest,
                        output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.refresh,
                ),
                "/codex.v1.AuthService/Logout": EndpointSync.unary(
                    method=MethodInfo(
                        name="Logout",
                        service_name="codex.v1.AuthService",
                        input=codex_dot_v1_dot_auth__pb2.LogoutRequest,
                        output=codex_dot_v1_dot_auth__pb2.LogoutResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.logout,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.AuthService"


class AuthServiceClientSync(ConnectClientSync):
    def login(
        self,
        request: codex_dot_v1_dot_auth__pb2.LoginRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Login",
                service_name="codex.v1.AuthService",
                input=codex_dot_v1_dot_auth__pb2.LoginRequest,
                output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def register(
        self,
        request: codex_dot_v1_dot_auth__pb2.RegisterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Register",
                service_name="codex.v1.AuthService",
                input=codex_dot_v1_dot_auth__pb2.RegisterRequest,
                output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def refresh(
        self,
        request: codex_dot_v1_dot_auth__pb2.RefreshRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_auth__pb2.LoginResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Refresh",
                service_name="codex.v1.AuthService",
                input=codex_dot_v1_dot_auth__pb2.RefreshRequest,
                output=codex_dot_v1_dot_auth__pb2.LoginResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def logout(
        self,
        request: codex_dot_v1_dot_auth__pb2.LogoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_auth__pb2.LogoutResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Logout",
                service_name="codex.v1.AuthService",
                input=codex_dot_v1_dot_auth__pb2.LogoutRequest,
                output=codex_dot_v1_dot_auth__pb2.LogoutResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


