# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/chat.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.chat_pb2 as codex_dot_v1_dot_chat__pb2
import codex.v1.common_pb2 as codex_dot_v1_dot_common__pb2


class ChatService(Protocol):
    async def list_chats(self, request: codex_dot_v1_dot_chat__pb2.ListChatsRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.ListChatsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_chat(self, request: codex_dot_v1_dot_chat__pb2.GetChatRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.Chat:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def rename_chat(self, request: codex_dot_v1_dot_chat__pb2.RenameChatRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.Chat:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_chat(self, request: codex_dot_v1_dot_chat__pb2.DeleteChatRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def run_turn(self, request: codex_dot_v1_dot_chat__pb2.RunTurnRequest, ctx: RequestContext) -> AsyncIterator[codex_dot_v1_dot_chat__pb2.ChatEvent]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def interrupt_turn(self, request: codex_dot_v1_dot_chat__pb2.InterruptTurnRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.InterruptTurnResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def steer_turn(self, request: codex_dot_v1_dot_chat__pb2.SteerTurnRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.SteerTurnResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_codex_usage(self, request: codex_dot_v1_dot_chat__pb2.GetCodexUsageRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.CodexUsage:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ChatServiceASGIApplication(ConnectASGIApplication[ChatService]):
    def __init__(self, service: ChatService | AsyncGenerator[ChatService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.ChatService/ListChats": Endpoint.unary(
                    method=MethodInfo(
                        name="ListChats",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.ListChatsRequest,
                        output=codex_dot_v1_dot_chat__pb2.ListChatsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_chats,
                ),
                "/codex.v1.ChatService/GetChat": Endpoint.unary(
                    method=MethodInfo(
                        name="GetChat",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.GetChatRequest,
                        output=codex_dot_v1_dot_chat__pb2.Chat,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_chat,
                ),
                "/codex.v1.ChatService/RenameChat": Endpoint.unary(
                    method=MethodInfo(
                        name="RenameChat",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.RenameChatRequest,
                        output=codex_dot_v1_dot_chat__pb2.Chat,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.rename_chat,
                ),
                "/codex.v1.ChatService/DeleteChat": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteChat",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.DeleteChatRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_chat,
                ),
                "/codex.v1.ChatService/RunTurn": Endpoint.server_stream(
                    method=MethodInfo(
                        name="RunTurn",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.RunTurnRequest,
                        output=codex_dot_v1_dot_chat__pb2.ChatEvent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.run_turn,
                ),
                "/codex.v1.ChatService/InterruptTurn": Endpoint.unary(
                    method=MethodInfo(
                        name="InterruptTurn",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.InterruptTurnRequest,
                        output=codex_dot_v1_dot_chat__pb2.InterruptTurnResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.interrupt_turn,
                ),
                "/codex.v1.ChatService/SteerTurn": Endpoint.unary(
                    method=MethodInfo(
                        name="SteerTurn",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.SteerTurnRequest,
                        output=codex_dot_v1_dot_chat__pb2.SteerTurnResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.steer_turn,
                ),
                "/codex.v1.ChatService/GetCodexUsage": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCodexUsage",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.GetCodexUsageRequest,
                        output=codex_dot_v1_dot_chat__pb2.CodexUsage,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_codex_usage,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.ChatService"


class ChatServiceClient(ConnectClient):
    async def list_chats(
        self,
        request: codex_dot_v1_dot_chat__pb2.ListChatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.ListChatsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListChats",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.ListChatsRequest,
                output=codex_dot_v1_dot_chat__pb2.ListChatsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_chat(
        self,
        request: codex_dot_v1_dot_chat__pb2.GetChatRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.Chat:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetChat",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.GetChatRequest,
                output=codex_dot_v1_dot_chat__pb2.Chat,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def rename_chat(
        self,
        request: codex_dot_v1_dot_chat__pb2.RenameChatRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.Chat:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RenameChat",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.RenameChatRequest,
                output=codex_dot_v1_dot_chat__pb2.Chat,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_chat(
        self,
        request: codex_dot_v1_dot_chat__pb2.DeleteChatRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteChat",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.DeleteChatRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def run_turn(
        self,
        request: codex_dot_v1_dot_chat__pb2.RunTurnRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[codex_dot_v1_dot_chat__pb2.ChatEvent]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="RunTurn",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.RunTurnRequest,
                output=codex_dot_v1_dot_chat__pb2.ChatEvent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def interrupt_turn(
        self,
        request: codex_dot_v1_dot_chat__pb2.InterruptTurnRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.InterruptTurnResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="InterruptTurn",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.InterruptTurnRequest,
                output=codex_dot_v1_dot_chat__pb2.InterruptTurnResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def steer_turn(
        self,
        request: codex_dot_v1_dot_chat__pb2.SteerTurnRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.SteerTurnResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SteerTurn",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.SteerTurnRequest,
                output=codex_dot_v1_dot_chat__pb2.SteerTurnResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_codex_usage(
        self,
        request: codex_dot_v1_dot_chat__pb2.GetCodexUsageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.CodexUsage:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCodexUsage",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.GetCodexUsageRequest,
                output=codex_dot_v1_dot_chat__pb2.CodexUsage,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class ChatServiceSync(Protocol):
    def list_chats(self, request: codex_dot_v1_dot_chat__pb2.ListChatsRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.ListChatsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_chat(self, request: codex_dot_v1_dot_chat__pb2.GetChatRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.Chat:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def rename_chat(self, request: codex_dot_v1_dot_chat__pb2.RenameChatRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.Chat:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_chat(self, request: codex_dot_v1_dot_chat__pb2.DeleteChatRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def run_turn(self, request: codex_dot_v1_dot_chat__pb2.RunTurnRequest, ctx: RequestContext) -> Iterator[codex_dot_v1_dot_chat__pb2.ChatEvent]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def interrupt_turn(self, request: codex_dot_v1_dot_chat__pb2.InterruptTurnRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.InterruptTurnResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def steer_turn(self, request: codex_dot_v1_dot_chat__pb2.SteerTurnRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.SteerTurnResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_codex_usage(self, request: codex_dot_v1_dot_chat__pb2.GetCodexUsageRequest, ctx: RequestContext) -> codex_dot_v1_dot_chat__pb2.CodexUsage:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ChatServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ChatServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.ChatService/ListChats": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListChats",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.ListChatsRequest,
                        output=codex_dot_v1_dot_chat__pb2.ListChatsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_chats,
                ),
                "/codex.v1.ChatService/GetChat": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetChat",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.GetChatRequest,
                        output=codex_dot_v1_dot_chat__pb2.Chat,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_chat,
                ),
                "/codex.v1.ChatService/RenameChat": EndpointSync.unary(
                    method=MethodInfo(
                        name="RenameChat",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.RenameChatRequest,
                        output=codex_dot_v1_dot_chat__pb2.Chat,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.rename_chat,
                ),
                "/codex.v1.ChatService/DeleteChat": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteChat",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.DeleteChatRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_chat,
                ),
                "/codex.v1.ChatService/RunTurn": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="RunTurn",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.RunTurnRequest,
                        output=codex_dot_v1_dot_chat__pb2.ChatEvent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.run_turn,
                ),
                "/codex.v1.ChatService/InterruptTurn": EndpointSync.unary(
                    method=MethodInfo(
                        name="InterruptTurn",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.InterruptTurnRequest,
                        output=codex_dot_v1_dot_chat__pb2.InterruptTurnResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.interrupt_turn,
                ),
                "/codex.v1.ChatService/SteerTurn": EndpointSync.unary(
                    method=MethodInfo(
                        name="SteerTurn",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.SteerTurnRequest,
                        output=codex_dot_v1_dot_chat__pb2.SteerTurnResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.steer_turn,
                ),
                "/codex.v1.ChatService/GetCodexUsage": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCodexUsage",
                        service_name="codex.v1.ChatService",
                        input=codex_dot_v1_dot_chat__pb2.GetCodexUsageRequest,
                        output=codex_dot_v1_dot_chat__pb2.CodexUsage,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_codex_usage,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.ChatService"


class ChatServiceClientSync(ConnectClientSync):
    def list_chats(
        self,
        request: codex_dot_v1_dot_chat__pb2.ListChatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.ListChatsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListChats",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.ListChatsRequest,
                output=codex_dot_v1_dot_chat__pb2.ListChatsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_chat(
        self,
        request: codex_dot_v1_dot_chat__pb2.GetChatRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.Chat:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetChat",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.GetChatRequest,
                output=codex_dot_v1_dot_chat__pb2.Chat,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def rename_chat(
        self,
        request: codex_dot_v1_dot_chat__pb2.RenameChatRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.Chat:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RenameChat",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.RenameChatRequest,
                output=codex_dot_v1_dot_chat__pb2.Chat,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_chat(
        self,
        request: codex_dot_v1_dot_chat__pb2.DeleteChatRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteChat",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.DeleteChatRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def run_turn(
        self,
        request: codex_dot_v1_dot_chat__pb2.RunTurnRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[codex_dot_v1_dot_chat__pb2.ChatEvent]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="RunTurn",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.RunTurnRequest,
                output=codex_dot_v1_dot_chat__pb2.ChatEvent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def interrupt_turn(
        self,
        request: codex_dot_v1_dot_chat__pb2.InterruptTurnRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.InterruptTurnResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="InterruptTurn",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.InterruptTurnRequest,
                output=codex_dot_v1_dot_chat__pb2.InterruptTurnResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def steer_turn(
        self,
        request: codex_dot_v1_dot_chat__pb2.SteerTurnRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.SteerTurnResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SteerTurn",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.SteerTurnRequest,
                output=codex_dot_v1_dot_chat__pb2.SteerTurnResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_codex_usage(
        self,
        request: codex_dot_v1_dot_chat__pb2.GetCodexUsageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_chat__pb2.CodexUsage:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCodexUsage",
                service_name="codex.v1.ChatService",
                input=codex_dot_v1_dot_chat__pb2.GetCodexUsageRequest,
                output=codex_dot_v1_dot_chat__pb2.CodexUsage,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


