# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: codex/v1/codex.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'codex/v1/codex.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63odex/v1/codex.proto\x12\x08\x63odex.v1\";\n\x15ReasoningEffortOption\x12\r\n\x05value\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\xbf\x01\n\nCodexModel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nis_default\x18\x04 \x01(\x08\x12 \n\x18\x64\x65\x66\x61ult_reasoning_effort\x18\x05 \x01(\t\x12\x44\n\x1bsupported_reasoning_efforts\x18\x06 \x03(\x0b\x32\x1f.codex.v1.ReasoningEffortOption\"\x13\n\x11ListModelsRequest\"]\n\x12ListModelsResponse\x12$\n\x06models\x18\x01 \x03(\x0b\x32\x14.codex.v1.CodexModel\x12!\n\x19\x66\x61llback_reasoning_effort\x18\x02 \x01(\t\"d\n\x10\x43odexPreferences\x12\x12\n\x05model\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10reasoning_effort\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_modelB\x13\n\x11_reasoning_effort\"\x17\n\x15GetPreferencesRequest\"l\n\x18UpdatePreferencesRequest\x12\x12\n\x05model\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10reasoning_effort\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_modelB\x13\n\x11_reasoning_effort2\xfb\x01\n\x0c\x43odexService\x12G\n\nListModels\x12\x1b.codex.v1.ListModelsRequest\x1a\x1c.codex.v1.ListModelsResponse\x12M\n\x0eGetPreferences\x12\x1f.codex.v1.GetPreferencesRequest\x1a\x1a.codex.v1.CodexPreferences\x12S\n\x11UpdatePreferences\x12\".codex.v1.UpdatePreferencesRequest\x1a\x1a.codex.v1.CodexPreferencesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codex.v1.codex_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REASONINGEFFORTOPTION']._serialized_start=34
  _globals['_REASONINGEFFORTOPTION']._serialized_end=93
  _globals['_CODEXMODEL']._serialized_start=96
  _globals['_CODEXMODEL']._serialized_end=287
  _globals['_LISTMODELSREQUEST']._serialized_start=289
  _globals['_LISTMODELSREQUEST']._serialized_end=308
  _globals['_LISTMODELSRESPONSE']._serialized_start=310
  _globals['_LISTMODELSRESPONSE']._serialized_end=403
  _globals['_CODEXPREFERENCES']._serialized_start=405
  _globals['_CODEXPREFERENCES']._serialized_end=505
  _globals['_GETPREFERENCESREQUEST']._serialized_start=507
  _globals['_GETPREFERENCESREQUEST']._serialized_end=530
  _globals['_UPDATEPREFERENCESREQUEST']._serialized_start=532
  _globals['_UPDATEPREFERENCESREQUEST']._serialized_end=640
  _globals['_CODEXSERVICE']._serialized_start=643
  _globals['_CODEXSERVICE']._serialized_end=894
# @@protoc_insertion_point(module_scope)
