# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/codex.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.codex_pb2 as codex_dot_v1_dot_codex__pb2


class CodexService(Protocol):
    async def list_models(self, request: codex_dot_v1_dot_codex__pb2.ListModelsRequest, ctx: RequestContext) -> codex_dot_v1_dot_codex__pb2.ListModelsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_preferences(self, request: codex_dot_v1_dot_codex__pb2.GetPreferencesRequest, ctx: RequestContext) -> codex_dot_v1_dot_codex__pb2.CodexPreferences:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_preferences(self, request: codex_dot_v1_dot_codex__pb2.UpdatePreferencesRequest, ctx: RequestContext) -> codex_dot_v1_dot_codex__pb2.CodexPreferences:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class CodexServiceASGIApplication(ConnectASGIApplication[CodexService]):
    def __init__(self, service: CodexService | AsyncGenerator[CodexService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.CodexService/ListModels": Endpoint.unary(
                    method=MethodInfo(
                        name="ListModels",
                        service_name="codex.v1.CodexService",
                        input=codex_dot_v1_dot_codex__pb2.ListModelsRequest,
                        output=codex_dot_v1_dot_codex__pb2.ListModelsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_models,
                ),
                "/codex.v1.CodexService/GetPreferences": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPreferences",
                        service_name="codex.v1.CodexService",
                        input=codex_dot_v1_dot_codex__pb2.GetPreferencesRequest,
                        output=codex_dot_v1_dot_codex__pb2.CodexPreferences,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_preferences,
                ),
                "/codex.v1.CodexService/UpdatePreferences": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdatePreferences",
                        service_name="codex.v1.CodexService",
                        input=codex_dot_v1_dot_codex__pb2.UpdatePreferencesRequest,
                        output=codex_dot_v1_dot_codex__pb2.CodexPreferences,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_preferences,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.CodexService"


class CodexServiceClient(ConnectClient):
    async def list_models(
        self,
        request: codex_dot_v1_dot_codex__pb2.ListModelsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_codex__pb2.ListModelsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListModels",
                service_name="codex.v1.CodexService",
                input=codex_dot_v1_dot_codex__pb2.ListModelsRequest,
                output=codex_dot_v1_dot_codex__pb2.ListModelsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_preferences(
        self,
        request: codex_dot_v1_dot_codex__pb2.GetPreferencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_codex__pb2.CodexPreferences:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPreferences",
                service_name="codex.v1.CodexService",
                input=codex_dot_v1_dot_codex__pb2.GetPreferencesRequest,
                output=codex_dot_v1_dot_codex__pb2.CodexPreferences,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_preferences(
        self,
        request: codex_dot_v1_dot_codex__pb2.UpdatePreferencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_codex__pb2.CodexPreferences:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePreferences",
                service_name="codex.v1.CodexService",
                input=codex_dot_v1_dot_codex__pb2.UpdatePreferencesRequest,
                output=codex_dot_v1_dot_codex__pb2.CodexPreferences,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class CodexServiceSync(Protocol):
    def list_models(self, request: codex_dot_v1_dot_codex__pb2.ListModelsRequest, ctx: RequestContext) -> codex_dot_v1_dot_codex__pb2.ListModelsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_preferences(self, request: codex_dot_v1_dot_codex__pb2.GetPreferencesRequest, ctx: RequestContext) -> codex_dot_v1_dot_codex__pb2.CodexPreferences:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_preferences(self, request: codex_dot_v1_dot_codex__pb2.UpdatePreferencesRequest, ctx: RequestContext) -> codex_dot_v1_dot_codex__pb2.CodexPreferences:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class CodexServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: CodexServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.CodexService/ListModels": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListModels",
                        service_name="codex.v1.CodexService",
                        input=codex_dot_v1_dot_codex__pb2.ListModelsRequest,
                        output=codex_dot_v1_dot_codex__pb2.ListModelsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_models,
                ),
                "/codex.v1.CodexService/GetPreferences": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPreferences",
                        service_name="codex.v1.CodexService",
                        input=codex_dot_v1_dot_codex__pb2.GetPreferencesRequest,
                        output=codex_dot_v1_dot_codex__pb2.CodexPreferences,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_preferences,
                ),
                "/codex.v1.CodexService/UpdatePreferences": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdatePreferences",
                        service_name="codex.v1.CodexService",
                        input=codex_dot_v1_dot_codex__pb2.UpdatePreferencesRequest,
                        output=codex_dot_v1_dot_codex__pb2.CodexPreferences,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_preferences,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.CodexService"


class CodexServiceClientSync(ConnectClientSync):
    def list_models(
        self,
        request: codex_dot_v1_dot_codex__pb2.ListModelsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_codex__pb2.ListModelsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListModels",
                service_name="codex.v1.CodexService",
                input=codex_dot_v1_dot_codex__pb2.ListModelsRequest,
                output=codex_dot_v1_dot_codex__pb2.ListModelsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_preferences(
        self,
        request: codex_dot_v1_dot_codex__pb2.GetPreferencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_codex__pb2.CodexPreferences:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPreferences",
                service_name="codex.v1.CodexService",
                input=codex_dot_v1_dot_codex__pb2.GetPreferencesRequest,
                output=codex_dot_v1_dot_codex__pb2.CodexPreferences,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_preferences(
        self,
        request: codex_dot_v1_dot_codex__pb2.UpdatePreferencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_codex__pb2.CodexPreferences:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePreferences",
                service_name="codex.v1.CodexService",
                input=codex_dot_v1_dot_codex__pb2.UpdatePreferencesRequest,
                output=codex_dot_v1_dot_codex__pb2.CodexPreferences,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


