# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: codex/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'codex/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63odex/v1/common.proto\x12\x08\x63odex.v1\"+\n\nPagination\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa3\x01\n\x13HealthCheckResponse\x12;\n\x06status\x18\x01 \x01(\x0e\x32+.codex.v1.HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\x32U\n\rHealthService\x12\x44\n\x05\x43heck\x12\x1c.codex.v1.HealthCheckRequest\x1a\x1d.codex.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codex.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAGINATION']._serialized_start=35
  _globals['_PAGINATION']._serialized_end=78
  _globals['_EMPTY']._serialized_start=80
  _globals['_EMPTY']._serialized_end=87
  _globals['_HEALTHCHECKREQUEST']._serialized_start=89
  _globals['_HEALTHCHECKREQUEST']._serialized_end=126
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=129
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=292
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=213
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=292
  _globals['_HEALTHSERVICE']._serialized_start=294
  _globals['_HEALTHSERVICE']._serialized_end=379
# @@protoc_insertion_point(module_scope)
