# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/common.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.common_pb2 as codex_dot_v1_dot_common__pb2


class HealthService(Protocol):
    async def check(self, request: codex_dot_v1_dot_common__pb2.HealthCheckRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.HealthCheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HealthServiceASGIApplication(ConnectASGIApplication[HealthService]):
    def __init__(self, service: HealthService | AsyncGenerator[HealthService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.HealthService/Check": Endpoint.unary(
                    method=MethodInfo(
                        name="Check",
                        service_name="codex.v1.HealthService",
                        input=codex_dot_v1_dot_common__pb2.HealthCheckRequest,
                        output=codex_dot_v1_dot_common__pb2.HealthCheckResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.HealthService"


class HealthServiceClient(ConnectClient):
    async def check(
        self,
        request: codex_dot_v1_dot_common__pb2.HealthCheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.HealthCheckResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Check",
                service_name="codex.v1.HealthService",
                input=codex_dot_v1_dot_common__pb2.HealthCheckRequest,
                output=codex_dot_v1_dot_common__pb2.HealthCheckResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class HealthServiceSync(Protocol):
    def check(self, request: codex_dot_v1_dot_common__pb2.HealthCheckRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.HealthCheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HealthServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: HealthServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.HealthService/Check": EndpointSync.unary(
                    method=MethodInfo(
                        name="Check",
                        service_name="codex.v1.HealthService",
                        input=codex_dot_v1_dot_common__pb2.HealthCheckRequest,
                        output=codex_dot_v1_dot_common__pb2.HealthCheckResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.HealthService"


class HealthServiceClientSync(ConnectClientSync):
    def check(
        self,
        request: codex_dot_v1_dot_common__pb2.HealthCheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.HealthCheckResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Check",
                service_name="codex.v1.HealthService",
                input=codex_dot_v1_dot_common__pb2.HealthCheckRequest,
                output=codex_dot_v1_dot_common__pb2.HealthCheckResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


