# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/event.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.event_pb2 as codex_dot_v1_dot_event__pb2


class EventService(Protocol):
    async def list_events(self, request: codex_dot_v1_dot_event__pb2.ListEventsRequest, ctx: RequestContext) -> codex_dot_v1_dot_event__pb2.ListEventsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EventServiceASGIApplication(ConnectASGIApplication[EventService]):
    def __init__(self, service: EventService | AsyncGenerator[EventService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.EventService/ListEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListEvents",
                        service_name="codex.v1.EventService",
                        input=codex_dot_v1_dot_event__pb2.ListEventsRequest,
                        output=codex_dot_v1_dot_event__pb2.ListEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_events,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.EventService"


class EventServiceClient(ConnectClient):
    async def list_events(
        self,
        request: codex_dot_v1_dot_event__pb2.ListEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_event__pb2.ListEventsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEvents",
                service_name="codex.v1.EventService",
                input=codex_dot_v1_dot_event__pb2.ListEventsRequest,
                output=codex_dot_v1_dot_event__pb2.ListEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class EventServiceSync(Protocol):
    def list_events(self, request: codex_dot_v1_dot_event__pb2.ListEventsRequest, ctx: RequestContext) -> codex_dot_v1_dot_event__pb2.ListEventsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EventServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: EventServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.EventService/ListEvents": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListEvents",
                        service_name="codex.v1.EventService",
                        input=codex_dot_v1_dot_event__pb2.ListEventsRequest,
                        output=codex_dot_v1_dot_event__pb2.ListEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_events,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.EventService"


class EventServiceClientSync(ConnectClientSync):
    def list_events(
        self,
        request: codex_dot_v1_dot_event__pb2.ListEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_event__pb2.ListEventsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEvents",
                service_name="codex.v1.EventService",
                input=codex_dot_v1_dot_event__pb2.ListEventsRequest,
                output=codex_dot_v1_dot_event__pb2.ListEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


