# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: codex/v1/event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'codex/v1/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from codex.v1 import common_pb2 as codex_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63odex/v1/event.proto\x12\x08\x63odex.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15\x63odex/v1/common.proto\"\xe5\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x07\x63hat_id\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\x14\n\x07user_id\x18\x03 \x01(\x03H\x01\x88\x01\x01\x12!\n\x04kind\x18\x04 \x01(\x0e\x32\x13.codex.v1.EventKind\x12-\n\x07payload\x18\x05 \x01(\x0b\x32\x17.google.protobuf.StructH\x02\x88\x01\x01\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\n\n\x08_chat_idB\n\n\x08_user_idB\n\n\x08_payload\"\x90\x01\n\x11ListEventsRequest\x12\x14\n\x07\x63hat_id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12&\n\x04kind\x18\x02 \x01(\x0e\x32\x13.codex.v1.EventKindH\x01\x88\x01\x01\x12(\n\npagination\x18\x03 \x01(\x0b\x32\x14.codex.v1.PaginationB\n\n\x08_chat_idB\x07\n\x05_kind\"5\n\x12ListEventsResponse\x12\x1f\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x0f.codex.v1.Event*\xd3\x02\n\tEventKind\x12\x1a\n\x16\x45VENT_KIND_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x45VENT_KIND_THREAD_OPENED\x10\x01\x12\x1b\n\x17\x45VENT_KIND_THREAD_RESET\x10\x02\x12\x1a\n\x16\x45VENT_KIND_THREAD_LOST\x10\x03\x12\x1b\n\x17\x45VENT_KIND_TURN_STARTED\x10\x04\x12\x1d\n\x19\x45VENT_KIND_TURN_COMPLETED\x10\x05\x12\x1f\n\x1b\x45VENT_KIND_TURN_INTERRUPTED\x10\x06\x12\x1a\n\x16\x45VENT_KIND_TURN_FAILED\x10\x07\x12\"\n\x1e\x45VENT_KIND_ATTACHMENT_RECEIVED\x10\x08\x12 \n\x1c\x45VENT_KIND_AUDIO_TRANSCRIBED\x10\t\x12\x14\n\x10\x45VENT_KIND_ERROR\x10\n2W\n\x0c\x45ventService\x12G\n\nListEvents\x12\x1b.codex.v1.ListEventsRequest\x1a\x1c.codex.v1.ListEventsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codex.v1.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTKIND']._serialized_start=555
  _globals['_EVENTKIND']._serialized_end=894
  _globals['_EVENT']._serialized_start=121
  _globals['_EVENT']._serialized_end=350
  _globals['_LISTEVENTSREQUEST']._serialized_start=353
  _globals['_LISTEVENTSREQUEST']._serialized_end=497
  _globals['_LISTEVENTSRESPONSE']._serialized_start=499
  _globals['_LISTEVENTSRESPONSE']._serialized_end=552
  _globals['_EVENTSERVICE']._serialized_start=896
  _globals['_EVENTSERVICE']._serialized_end=983
# @@protoc_insertion_point(module_scope)
