# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/message.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.message_pb2 as codex_dot_v1_dot_message__pb2


class MessageService(Protocol):
    async def list_messages(self, request: codex_dot_v1_dot_message__pb2.ListMessagesRequest, ctx: RequestContext) -> codex_dot_v1_dot_message__pb2.ListMessagesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class MessageServiceASGIApplication(ConnectASGIApplication[MessageService]):
    def __init__(self, service: MessageService | AsyncGenerator[MessageService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.MessageService/ListMessages": Endpoint.unary(
                    method=MethodInfo(
                        name="ListMessages",
                        service_name="codex.v1.MessageService",
                        input=codex_dot_v1_dot_message__pb2.ListMessagesRequest,
                        output=codex_dot_v1_dot_message__pb2.ListMessagesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_messages,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.MessageService"


class MessageServiceClient(ConnectClient):
    async def list_messages(
        self,
        request: codex_dot_v1_dot_message__pb2.ListMessagesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_message__pb2.ListMessagesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMessages",
                service_name="codex.v1.MessageService",
                input=codex_dot_v1_dot_message__pb2.ListMessagesRequest,
                output=codex_dot_v1_dot_message__pb2.ListMessagesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class MessageServiceSync(Protocol):
    def list_messages(self, request: codex_dot_v1_dot_message__pb2.ListMessagesRequest, ctx: RequestContext) -> codex_dot_v1_dot_message__pb2.ListMessagesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class MessageServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: MessageServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.MessageService/ListMessages": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListMessages",
                        service_name="codex.v1.MessageService",
                        input=codex_dot_v1_dot_message__pb2.ListMessagesRequest,
                        output=codex_dot_v1_dot_message__pb2.ListMessagesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_messages,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.MessageService"


class MessageServiceClientSync(ConnectClientSync):
    def list_messages(
        self,
        request: codex_dot_v1_dot_message__pb2.ListMessagesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_message__pb2.ListMessagesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMessages",
                service_name="codex.v1.MessageService",
                input=codex_dot_v1_dot_message__pb2.ListMessagesRequest,
                output=codex_dot_v1_dot_message__pb2.ListMessagesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


