# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: codex/v1/notes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'codex/v1/notes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from codex.v1 import common_pb2 as codex_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63odex/v1/notes.proto\x12\x08\x63odex.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15\x63odex/v1/common.proto\"\x9d\x01\n\x04Note\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"T\n\x0fSaveNoteRequest\x12\x0f\n\x02id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\tB\x05\n\x03_id\"\x1c\n\x0eGetNoteRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"[\n\x12SearchNotesRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12(\n\npagination\x18\x03 \x01(\x0b\x32\x14.codex.v1.Pagination\"5\n\x07NoteHit\x12\x1c\n\x04note\x18\x01 \x01(\x0b\x32\x0e.codex.v1.Note\x12\x0c\n\x04rank\x18\x02 \x01(\x02\"6\n\x13SearchNotesResponse\x12\x1f\n\x04hits\x18\x01 \x03(\x0b\x32\x11.codex.v1.NoteHit\"J\n\x10ListNotesRequest\x12\x0c\n\x04tags\x18\x01 \x03(\t\x12(\n\npagination\x18\x02 \x01(\x0b\x32\x14.codex.v1.Pagination\"2\n\x11ListNotesResponse\x12\x1d\n\x05notes\x18\x01 \x03(\x0b\x32\x0e.codex.v1.Note\"\x1f\n\x11\x44\x65leteNoteRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xc8\x02\n\x0cNotesService\x12\x35\n\x08SaveNote\x12\x19.codex.v1.SaveNoteRequest\x1a\x0e.codex.v1.Note\x12\x33\n\x07GetNote\x12\x18.codex.v1.GetNoteRequest\x1a\x0e.codex.v1.Note\x12J\n\x0bSearchNotes\x12\x1c.codex.v1.SearchNotesRequest\x1a\x1d.codex.v1.SearchNotesResponse\x12\x44\n\tListNotes\x12\x1a.codex.v1.ListNotesRequest\x1a\x1b.codex.v1.ListNotesResponse\x12:\n\nDeleteNote\x12\x1b.codex.v1.DeleteNoteRequest\x1a\x0f.codex.v1.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codex.v1.notes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTE']._serialized_start=91
  _globals['_NOTE']._serialized_end=248
  _globals['_SAVENOTEREQUEST']._serialized_start=250
  _globals['_SAVENOTEREQUEST']._serialized_end=334
  _globals['_GETNOTEREQUEST']._serialized_start=336
  _globals['_GETNOTEREQUEST']._serialized_end=364
  _globals['_SEARCHNOTESREQUEST']._serialized_start=366
  _globals['_SEARCHNOTESREQUEST']._serialized_end=457
  _globals['_NOTEHIT']._serialized_start=459
  _globals['_NOTEHIT']._serialized_end=512
  _globals['_SEARCHNOTESRESPONSE']._serialized_start=514
  _globals['_SEARCHNOTESRESPONSE']._serialized_end=568
  _globals['_LISTNOTESREQUEST']._serialized_start=570
  _globals['_LISTNOTESREQUEST']._serialized_end=644
  _globals['_LISTNOTESRESPONSE']._serialized_start=646
  _globals['_LISTNOTESRESPONSE']._serialized_end=696
  _globals['_DELETENOTEREQUEST']._serialized_start=698
  _globals['_DELETENOTEREQUEST']._serialized_end=729
  _globals['_NOTESSERVICE']._serialized_start=732
  _globals['_NOTESSERVICE']._serialized_end=1060
# @@protoc_insertion_point(module_scope)
