# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/notes.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.common_pb2 as codex_dot_v1_dot_common__pb2
import codex.v1.notes_pb2 as codex_dot_v1_dot_notes__pb2


class NotesService(Protocol):
    async def save_note(self, request: codex_dot_v1_dot_notes__pb2.SaveNoteRequest, ctx: RequestContext) -> codex_dot_v1_dot_notes__pb2.Note:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_note(self, request: codex_dot_v1_dot_notes__pb2.GetNoteRequest, ctx: RequestContext) -> codex_dot_v1_dot_notes__pb2.Note:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def search_notes(self, request: codex_dot_v1_dot_notes__pb2.SearchNotesRequest, ctx: RequestContext) -> codex_dot_v1_dot_notes__pb2.SearchNotesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_notes(self, request: codex_dot_v1_dot_notes__pb2.ListNotesRequest, ctx: RequestContext) -> codex_dot_v1_dot_notes__pb2.ListNotesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_note(self, request: codex_dot_v1_dot_notes__pb2.DeleteNoteRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NotesServiceASGIApplication(ConnectASGIApplication[NotesService]):
    def __init__(self, service: NotesService | AsyncGenerator[NotesService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.NotesService/SaveNote": Endpoint.unary(
                    method=MethodInfo(
                        name="SaveNote",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.SaveNoteRequest,
                        output=codex_dot_v1_dot_notes__pb2.Note,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.save_note,
                ),
                "/codex.v1.NotesService/GetNote": Endpoint.unary(
                    method=MethodInfo(
                        name="GetNote",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.GetNoteRequest,
                        output=codex_dot_v1_dot_notes__pb2.Note,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_note,
                ),
                "/codex.v1.NotesService/SearchNotes": Endpoint.unary(
                    method=MethodInfo(
                        name="SearchNotes",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.SearchNotesRequest,
                        output=codex_dot_v1_dot_notes__pb2.SearchNotesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.search_notes,
                ),
                "/codex.v1.NotesService/ListNotes": Endpoint.unary(
                    method=MethodInfo(
                        name="ListNotes",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.ListNotesRequest,
                        output=codex_dot_v1_dot_notes__pb2.ListNotesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_notes,
                ),
                "/codex.v1.NotesService/DeleteNote": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteNote",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.DeleteNoteRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_note,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.NotesService"


class NotesServiceClient(ConnectClient):
    async def save_note(
        self,
        request: codex_dot_v1_dot_notes__pb2.SaveNoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_notes__pb2.Note:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SaveNote",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.SaveNoteRequest,
                output=codex_dot_v1_dot_notes__pb2.Note,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_note(
        self,
        request: codex_dot_v1_dot_notes__pb2.GetNoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_notes__pb2.Note:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNote",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.GetNoteRequest,
                output=codex_dot_v1_dot_notes__pb2.Note,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def search_notes(
        self,
        request: codex_dot_v1_dot_notes__pb2.SearchNotesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_notes__pb2.SearchNotesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SearchNotes",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.SearchNotesRequest,
                output=codex_dot_v1_dot_notes__pb2.SearchNotesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_notes(
        self,
        request: codex_dot_v1_dot_notes__pb2.ListNotesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_notes__pb2.ListNotesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNotes",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.ListNotesRequest,
                output=codex_dot_v1_dot_notes__pb2.ListNotesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_note(
        self,
        request: codex_dot_v1_dot_notes__pb2.DeleteNoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteNote",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.DeleteNoteRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class NotesServiceSync(Protocol):
    def save_note(self, request: codex_dot_v1_dot_notes__pb2.SaveNoteRequest, ctx: RequestContext) -> codex_dot_v1_dot_notes__pb2.Note:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_note(self, request: codex_dot_v1_dot_notes__pb2.GetNoteRequest, ctx: RequestContext) -> codex_dot_v1_dot_notes__pb2.Note:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def search_notes(self, request: codex_dot_v1_dot_notes__pb2.SearchNotesRequest, ctx: RequestContext) -> codex_dot_v1_dot_notes__pb2.SearchNotesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_notes(self, request: codex_dot_v1_dot_notes__pb2.ListNotesRequest, ctx: RequestContext) -> codex_dot_v1_dot_notes__pb2.ListNotesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_note(self, request: codex_dot_v1_dot_notes__pb2.DeleteNoteRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NotesServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: NotesServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.NotesService/SaveNote": EndpointSync.unary(
                    method=MethodInfo(
                        name="SaveNote",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.SaveNoteRequest,
                        output=codex_dot_v1_dot_notes__pb2.Note,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.save_note,
                ),
                "/codex.v1.NotesService/GetNote": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetNote",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.GetNoteRequest,
                        output=codex_dot_v1_dot_notes__pb2.Note,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_note,
                ),
                "/codex.v1.NotesService/SearchNotes": EndpointSync.unary(
                    method=MethodInfo(
                        name="SearchNotes",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.SearchNotesRequest,
                        output=codex_dot_v1_dot_notes__pb2.SearchNotesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.search_notes,
                ),
                "/codex.v1.NotesService/ListNotes": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListNotes",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.ListNotesRequest,
                        output=codex_dot_v1_dot_notes__pb2.ListNotesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_notes,
                ),
                "/codex.v1.NotesService/DeleteNote": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteNote",
                        service_name="codex.v1.NotesService",
                        input=codex_dot_v1_dot_notes__pb2.DeleteNoteRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_note,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.NotesService"


class NotesServiceClientSync(ConnectClientSync):
    def save_note(
        self,
        request: codex_dot_v1_dot_notes__pb2.SaveNoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_notes__pb2.Note:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SaveNote",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.SaveNoteRequest,
                output=codex_dot_v1_dot_notes__pb2.Note,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_note(
        self,
        request: codex_dot_v1_dot_notes__pb2.GetNoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_notes__pb2.Note:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNote",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.GetNoteRequest,
                output=codex_dot_v1_dot_notes__pb2.Note,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def search_notes(
        self,
        request: codex_dot_v1_dot_notes__pb2.SearchNotesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_notes__pb2.SearchNotesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SearchNotes",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.SearchNotesRequest,
                output=codex_dot_v1_dot_notes__pb2.SearchNotesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_notes(
        self,
        request: codex_dot_v1_dot_notes__pb2.ListNotesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_notes__pb2.ListNotesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNotes",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.ListNotesRequest,
                output=codex_dot_v1_dot_notes__pb2.ListNotesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_note(
        self,
        request: codex_dot_v1_dot_notes__pb2.DeleteNoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteNote",
                service_name="codex.v1.NotesService",
                input=codex_dot_v1_dot_notes__pb2.DeleteNoteRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


