# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/uploads.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.common_pb2 as codex_dot_v1_dot_common__pb2
import codex.v1.uploads_pb2 as codex_dot_v1_dot_uploads__pb2


class UploadsService(Protocol):
    async def upload_once(self, request: codex_dot_v1_dot_uploads__pb2.UploadOnceRequest, ctx: RequestContext) -> codex_dot_v1_dot_uploads__pb2.UploadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_presigned(self, request: codex_dot_v1_dot_uploads__pb2.GetPresignedRequest, ctx: RequestContext) -> codex_dot_v1_dot_uploads__pb2.GetPresignedResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_uploads(self, request: codex_dot_v1_dot_uploads__pb2.ListUploadsRequest, ctx: RequestContext) -> codex_dot_v1_dot_uploads__pb2.ListUploadsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_upload(self, request: codex_dot_v1_dot_uploads__pb2.DeleteUploadRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class UploadsServiceASGIApplication(ConnectASGIApplication[UploadsService]):
    def __init__(self, service: UploadsService | AsyncGenerator[UploadsService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.UploadsService/UploadOnce": Endpoint.unary(
                    method=MethodInfo(
                        name="UploadOnce",
                        service_name="codex.v1.UploadsService",
                        input=codex_dot_v1_dot_uploads__pb2.UploadOnceRequest,
                        output=codex_dot_v1_dot_uploads__pb2.UploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.upload_once,
                ),
                "/codex.v1.UploadsService/GetPresigned": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPresigned",
                        service_name="codex.v1.UploadsService",
                        input=codex_dot_v1_dot_uploads__pb2.GetPresignedRequest,
                        output=codex_dot_v1_dot_uploads__pb2.GetPresignedResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_presigned,
                ),
                "/codex.v1.UploadsService/ListUploads": Endpoint.unary(
                    method=MethodInfo(
                        name="ListUploads",
                        service_name="codex.v1.UploadsService",
                        input=codex_dot_v1_dot_uploads__pb2.ListUploadsRequest,
                        output=codex_dot_v1_dot_uploads__pb2.ListUploadsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_uploads,
                ),
                "/codex.v1.UploadsService/DeleteUpload": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteUpload",
                        service_name="codex.v1.UploadsService",
                        input=codex_dot_v1_dot_uploads__pb2.DeleteUploadRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_upload,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.UploadsService"


class UploadsServiceClient(ConnectClient):
    async def upload_once(
        self,
        request: codex_dot_v1_dot_uploads__pb2.UploadOnceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_uploads__pb2.UploadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadOnce",
                service_name="codex.v1.UploadsService",
                input=codex_dot_v1_dot_uploads__pb2.UploadOnceRequest,
                output=codex_dot_v1_dot_uploads__pb2.UploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_presigned(
        self,
        request: codex_dot_v1_dot_uploads__pb2.GetPresignedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_uploads__pb2.GetPresignedResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPresigned",
                service_name="codex.v1.UploadsService",
                input=codex_dot_v1_dot_uploads__pb2.GetPresignedRequest,
                output=codex_dot_v1_dot_uploads__pb2.GetPresignedResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_uploads(
        self,
        request: codex_dot_v1_dot_uploads__pb2.ListUploadsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_uploads__pb2.ListUploadsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUploads",
                service_name="codex.v1.UploadsService",
                input=codex_dot_v1_dot_uploads__pb2.ListUploadsRequest,
                output=codex_dot_v1_dot_uploads__pb2.ListUploadsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_upload(
        self,
        request: codex_dot_v1_dot_uploads__pb2.DeleteUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteUpload",
                service_name="codex.v1.UploadsService",
                input=codex_dot_v1_dot_uploads__pb2.DeleteUploadRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class UploadsServiceSync(Protocol):
    def upload_once(self, request: codex_dot_v1_dot_uploads__pb2.UploadOnceRequest, ctx: RequestContext) -> codex_dot_v1_dot_uploads__pb2.UploadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_presigned(self, request: codex_dot_v1_dot_uploads__pb2.GetPresignedRequest, ctx: RequestContext) -> codex_dot_v1_dot_uploads__pb2.GetPresignedResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_uploads(self, request: codex_dot_v1_dot_uploads__pb2.ListUploadsRequest, ctx: RequestContext) -> codex_dot_v1_dot_uploads__pb2.ListUploadsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_upload(self, request: codex_dot_v1_dot_uploads__pb2.DeleteUploadRequest, ctx: RequestContext) -> codex_dot_v1_dot_common__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class UploadsServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: UploadsServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.UploadsService/UploadOnce": EndpointSync.unary(
                    method=MethodInfo(
                        name="UploadOnce",
                        service_name="codex.v1.UploadsService",
                        input=codex_dot_v1_dot_uploads__pb2.UploadOnceRequest,
                        output=codex_dot_v1_dot_uploads__pb2.UploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.upload_once,
                ),
                "/codex.v1.UploadsService/GetPresigned": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPresigned",
                        service_name="codex.v1.UploadsService",
                        input=codex_dot_v1_dot_uploads__pb2.GetPresignedRequest,
                        output=codex_dot_v1_dot_uploads__pb2.GetPresignedResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_presigned,
                ),
                "/codex.v1.UploadsService/ListUploads": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListUploads",
                        service_name="codex.v1.UploadsService",
                        input=codex_dot_v1_dot_uploads__pb2.ListUploadsRequest,
                        output=codex_dot_v1_dot_uploads__pb2.ListUploadsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_uploads,
                ),
                "/codex.v1.UploadsService/DeleteUpload": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteUpload",
                        service_name="codex.v1.UploadsService",
                        input=codex_dot_v1_dot_uploads__pb2.DeleteUploadRequest,
                        output=codex_dot_v1_dot_common__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_upload,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.UploadsService"


class UploadsServiceClientSync(ConnectClientSync):
    def upload_once(
        self,
        request: codex_dot_v1_dot_uploads__pb2.UploadOnceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_uploads__pb2.UploadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadOnce",
                service_name="codex.v1.UploadsService",
                input=codex_dot_v1_dot_uploads__pb2.UploadOnceRequest,
                output=codex_dot_v1_dot_uploads__pb2.UploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_presigned(
        self,
        request: codex_dot_v1_dot_uploads__pb2.GetPresignedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_uploads__pb2.GetPresignedResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPresigned",
                service_name="codex.v1.UploadsService",
                input=codex_dot_v1_dot_uploads__pb2.GetPresignedRequest,
                output=codex_dot_v1_dot_uploads__pb2.GetPresignedResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_uploads(
        self,
        request: codex_dot_v1_dot_uploads__pb2.ListUploadsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_uploads__pb2.ListUploadsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUploads",
                service_name="codex.v1.UploadsService",
                input=codex_dot_v1_dot_uploads__pb2.ListUploadsRequest,
                output=codex_dot_v1_dot_uploads__pb2.ListUploadsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_upload(
        self,
        request: codex_dot_v1_dot_uploads__pb2.DeleteUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_common__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteUpload",
                service_name="codex.v1.UploadsService",
                input=codex_dot_v1_dot_uploads__pb2.DeleteUploadRequest,
                output=codex_dot_v1_dot_common__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


