# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codex/v1/user.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codex.v1.user_pb2 as codex_dot_v1_dot_user__pb2


class UserService(Protocol):
    async def me(self, request: codex_dot_v1_dot_user__pb2.MeRequest, ctx: RequestContext) -> codex_dot_v1_dot_user__pb2.User:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_me(self, request: codex_dot_v1_dot_user__pb2.UpdateMeRequest, ctx: RequestContext) -> codex_dot_v1_dot_user__pb2.User:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class UserServiceASGIApplication(ConnectASGIApplication[UserService]):
    def __init__(self, service: UserService | AsyncGenerator[UserService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codex.v1.UserService/Me": Endpoint.unary(
                    method=MethodInfo(
                        name="Me",
                        service_name="codex.v1.UserService",
                        input=codex_dot_v1_dot_user__pb2.MeRequest,
                        output=codex_dot_v1_dot_user__pb2.User,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.me,
                ),
                "/codex.v1.UserService/UpdateMe": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateMe",
                        service_name="codex.v1.UserService",
                        input=codex_dot_v1_dot_user__pb2.UpdateMeRequest,
                        output=codex_dot_v1_dot_user__pb2.User,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_me,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.UserService"


class UserServiceClient(ConnectClient):
    async def me(
        self,
        request: codex_dot_v1_dot_user__pb2.MeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_user__pb2.User:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Me",
                service_name="codex.v1.UserService",
                input=codex_dot_v1_dot_user__pb2.MeRequest,
                output=codex_dot_v1_dot_user__pb2.User,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_me(
        self,
        request: codex_dot_v1_dot_user__pb2.UpdateMeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_user__pb2.User:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateMe",
                service_name="codex.v1.UserService",
                input=codex_dot_v1_dot_user__pb2.UpdateMeRequest,
                output=codex_dot_v1_dot_user__pb2.User,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class UserServiceSync(Protocol):
    def me(self, request: codex_dot_v1_dot_user__pb2.MeRequest, ctx: RequestContext) -> codex_dot_v1_dot_user__pb2.User:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_me(self, request: codex_dot_v1_dot_user__pb2.UpdateMeRequest, ctx: RequestContext) -> codex_dot_v1_dot_user__pb2.User:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class UserServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: UserServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codex.v1.UserService/Me": EndpointSync.unary(
                    method=MethodInfo(
                        name="Me",
                        service_name="codex.v1.UserService",
                        input=codex_dot_v1_dot_user__pb2.MeRequest,
                        output=codex_dot_v1_dot_user__pb2.User,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.me,
                ),
                "/codex.v1.UserService/UpdateMe": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateMe",
                        service_name="codex.v1.UserService",
                        input=codex_dot_v1_dot_user__pb2.UpdateMeRequest,
                        output=codex_dot_v1_dot_user__pb2.User,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_me,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codex.v1.UserService"


class UserServiceClientSync(ConnectClientSync):
    def me(
        self,
        request: codex_dot_v1_dot_user__pb2.MeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_user__pb2.User:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Me",
                service_name="codex.v1.UserService",
                input=codex_dot_v1_dot_user__pb2.MeRequest,
                output=codex_dot_v1_dot_user__pb2.User,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_me(
        self,
        request: codex_dot_v1_dot_user__pb2.UpdateMeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codex_dot_v1_dot_user__pb2.User:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateMe",
                service_name="codex.v1.UserService",
                input=codex_dot_v1_dot_user__pb2.UpdateMeRequest,
                output=codex_dot_v1_dot_user__pb2.User,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


